name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest


    container:
      image: iantorres/boosted:1.87.0-debug


    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: copper
          MYSQL_USER: user
          MYSQL_PASSWORD: user_password
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      redis:
        image: bitnami/redis:latest
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          ALLOW_EMPTY_PASSWORD: yes

    steps:
      - uses: actions/checkout@v4
      - run: |
          ping 127.0.0.1
          apt update
          apt install -y lcov
          curl -Os https://cli.codecov.io/latest/linux/codecov
          chmod +x codecov
          mkdir build
          cd build
          cmake .. -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug
          make -j4
          cd ../bin
          ./tests
          cd ..
          lcov --capture --directory . --output-file coverage.info
          lcov --list coverage.info
        env:
          DATABASE_HOST: 127.0.0.1
          DATABASE_USER: user
          DATABASE_PASSWORD: user_password
          DATABASE_NAME: copper
          DATABASE_PORT: ${{ job.services.mysql.ports[3306] }}
          REDIS_HOST: redis
          REDIS_PORT: 6379

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: true
          files: ./coverage.info
