name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest


    container:
      image: iantorres/boosted:1.87.0-debug

    steps:
      - uses: actions/checkout@v4
      - run: |
          apt update
          apt install -y lcov
          curl -Os https://cli.codecov.io/latest/linux/codecov
          chmod +x codecov
          mkdir build
          cd build
          cmake .. -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug
          make
          cd ../bin
          ./tests
          cd ..
          lcov --capture --directory . --output-file coverage.info
          lcov --list coverage.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: true
          files: ./coverage.info
